### ISSUE TITLE
Libraries associated with languages

### ISSUE THREAD

**Issue by lwasser** [earthlab/dev-earthlab-site#28]
Ok - now we have a final workflow to figure out. We have lots of lessons that use lots of libraries. We need code to query the lessons and create a list like this of libraries. Now i understand this will be difficult because we don't have nested lists that differentiate between R and python.

Here is the YAML list now.

```
- lang: python
  libs:
    - rpy2
    - h5py
- lang: r
  libs:
    - raster
    - rhdf5
    - base
- lang: javascript
  libs:
```

I added javascript. But we need

1. to have each library listed in it's appropriate spot
2. to have each library have an associated .md file in the : https://github.com/earthlab/dev-earthlab-site/tree/master/org/lang-lib directory 

So... what is our workflow? I'll get the code working (it's not currently) and will create a few seed pages. Maybe we just auto generate a library list using my rmd code? And there are only a few lessons that have two languages so actually it won't be too hard to look at language and then library and generate a list like the one above but that maybe also has a fourth category (R & python) ? thoughts @mbjoseph   

Sorry i'm bombarding you with issues! just trying to knock this out so we can push the site live.
